name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: pytest -q

  # OPTIONAL: E2E tests with live OpenAI API (disabled by default)
  # Uncomment and configure OPENAI_API_KEY secret to enable
  # test-e2e:
  #   runs-on: ubuntu-latest
  #   if: false  # Set to true to enable E2E tests
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     
  #   - name: Set up Python 3.11
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.11'
  #       cache: 'pip'
  #       
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       
  #   - name: Run E2E tests
  #     env:
  #       LIVE_E2E: 1
  #       OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  #     run: pytest -m e2e -q